Organizations:
  - &OrdererOrg
    Name: Orderer
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &ru
    Name: ruMSP
    ID: ruMSP
    MSPDir: crypto-config/peerOrganizations/ru.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ruMSP.admin', 'ruMSP.peer', 'ruMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ruMSP.admin', 'ruMSP.peer', 'ruMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ruMSP.admin')"
    AnchorPeers:
      - Host: peer0.ru.com
        Port: 7051

  - &me
    Name: meMSP
    ID: meMSP
    MSPDir: crypto-config/peerOrganizations/me.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('meMSP.admin', 'meMSP.peer', 'meMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('meMSP.admin', 'meMSP.peer', 'meMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('meMSP.admin')"
    AnchorPeers:
      - Host: peer0.me.com
        Port: 9051

  - &authenticator
    Name: authenticatorMSP
    ID: authenticatorMSP
    MSPDir: crypto-config/peerOrganizations/authenticator.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('authenticatorMSP.admin', 'authenticatorMSP.peer', 'authenticatorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('authenticatorMSP.admin', 'authenticatorMSP.peer', 'authenticatorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('authenticatorMSP.admin')"
    AnchorPeers:
      - Host: peer0.authenticator.com
        Port: 11051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies: &ApplicationDefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: Signature
      Rule: "OR('ruMSP.member', 'meMSP.member', 'authenticatorMSP.member')"
    Endorsement:
      Type: Signature
      Rule: "OR('ruMSP.member', 'meMSP.member', 'authenticatorMSP.member')"


Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Capabilities: *OrdererCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities


Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      CertificationConsortium:
        Organizations:
          - *ru
          - *me
          - *authenticator

  CertificationChannel:
    Consortium: CertificationConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ru
        - *me
        - *authenticator
      Capabilities:
        <<: *ApplicationCapabilities

