OrdererOrgs:
  - Name: Orderer
    Domain: com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: ru
   Domain: ru.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: me
   Domain: me.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: authenticator
   Domain: authenticator.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
