version: '2'

volumes:
  orderer.certification-network.com:
  peer0.iit.certification-network.com:
  peer1.iit.certification-network.com:
  peer0.mhrd.certification-network.com:
  peer1.mhrd.certification-network.com:
  peer0.upgrad.certification-network.com:
  peer1.upgrad.certification-network.com:

networks:
  certification:

services:

  ca.iit.certification-network.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.iit.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/iit.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.iit.certification-network.com
    networks:
      - certification

  ca.mhrd.certification-network.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.mhrd.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/mhrd.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.mhrd.certification-network.com
    networks:
      - certification

  ca.upgrad.certification-network.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.upgrad.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/upgrad.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.upgrad.certification-network.com
    networks:
      - certification

  orderer.certification-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.certification-network.com
    container_name: orderer.certification-network.com
    networks:
      - certification

  peer0.iit.certification-network.com:
    container_name: peer0.iit.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.iit.certification-network.com
    networks:
      - certification

  peer1.iit.certification-network.com:
    container_name: peer1.iit.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.iit.certification-network.com
    networks:
      - certification

  peer0.mhrd.certification-network.com:
    container_name: peer0.mhrd.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.mhrd.certification-network.com
    networks:
      - certification

  peer1.mhrd.certification-network.com:
    container_name: peer1.mhrd.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.mhrd.certification-network.com
    networks:
      - certification

  peer0.upgrad.certification-network.com:
    container_name: peer0.upgrad.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.upgrad.certification-network.com
    networks:
      - certification

  peer1.upgrad.certification-network.com:
    container_name: peer1.upgrad.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.upgrad.certification-network.com
    networks:
      - certification

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        # Mounting the new Go chaincode directory
        - ./../chaincode-go/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.certification-network.com
      - peer0.iit.certification-network.com
      - peer1.iit.certification-network.com
      - peer0.mhrd.certification-network.com
      - peer1.mhrd.certification-network.com
      - peer0.upgrad.certification-network.com
      - peer1.upgrad.certification-network.com
    networks:
      - certification
