version: '2'

volumes:
  orderer.com:
  peer0.ru.com:
  peer1.ru.com:
  peer0.me.com:
  peer1.me.com:
  peer0.authenticator.com:
  peer1.authenticator.com:

networks:
  certification:
    name: network_certification

services:
  ca.ru.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ru.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ru.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ru.com
    networks:
      - certification

  ca.me.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.me.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/me.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.me.com
    networks:
      - certification

  ca.authenticator.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.authenticator.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/authenticator.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.authenticator.com
    networks:
      - certification

  orderer.com:
    extends:
      file: docker-base/docker-compose-base.yaml
      service: orderer.com
    container_name: orderer.com
    networks:
      - certification

  peer0.ru.com:
    container_name: peer0.ru.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.ru.com
    networks:
      - certification

  peer1.ru.com:
    container_name: peer1.ru.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.ru.com
    networks:
      - certification

  peer0.me.com:
    container_name: peer0.me.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.me.com
    networks:
      - certification

  peer1.me.com:
    container_name: peer1.me.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.me.com
    networks:
      - certification

  peer0.authenticator.com:
    container_name: peer0.authenticator.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer0.authenticator.com
    networks:
      - certification

  peer1.authenticator.com:
    container_name: peer1.authenticator.com
    extends:
      file: docker-base/docker-compose-base.yaml
      service: peer1.authenticator.com
    networks:
      - certification

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode-go/:/opt/gopath/src/github.com/chaincode # Mount the new Go chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.com
      - peer0.ru.com
      - peer1.ru.com
      - peer0.me.com
      - peer1.me.com
      - peer0.authenticator.com
      - peer1.authenticator.com
    networks:
      - certification
