version: '2'

volumes:
  orderer.com:
  peer0.ru.com:
  peer1.ru.com:
  peer0.me.com:
  peer1.me.com:
  peer0.authenticator.com:
  peer1.authenticator.com:

networks:
  certification:

services:

  ca.ru.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ru.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ru.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ru_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ru.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ru_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ru.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ru.com
    networks:
      - certification

  ca.me.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.me.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.me.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/me_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.me.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/me_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/me.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.me.com
    networks:
      - certification

  ca.authenticator.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.authenticator.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.authenticator.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/authenticator_CA_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.authenticator.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/authenticator_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/authenticator.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.authenticator.com
    networks:
      - certification

  orderer.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.com
    container_name: orderer.com
    networks:
      - certification

  peer0.ru.com:
    container_name: peer0.ru.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.ru.com
    networks:
      - certification

  peer1.ru.com:
    container_name: peer1.ru.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.ru.com
    networks:
      - certification

  peer0.me.com:
    container_name: peer0.me.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.me.com
    networks:
      - certification

  peer1.me.com:
    container_name: peer1.me.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.me.com
    networks:
      - certification

  peer0.authenticator.com:
    container_name: peer0.authenticator.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.authenticator.com
    networks:
      - certification

  peer1.authenticator.com:
    container_name: peer1.authenticator.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.authenticator.com
    networks:
      - certification

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ru.com:7051
      - CORE_PEER_LOCALMSPID=ruMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ru.com/peers/peer0.ru.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ru.com/peers/peer0.ru.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ru.com/peers/peer0.ru.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ru.com/users/Admin@ru.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
   #   - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.ru.com
      - ca.me.com
      - ca.authenticator.com
      - orderer.com
      - peer0.ru.com
      - peer1.ru.com
      - peer0.me.com
      - peer1.me.com
      - peer0.authenticator.com
      - peer1.authenticator.com
    networks:
      - certification

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.ru.com:7051
      - CORE_PEER_LOCALMSPID=ruMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/ru.com/users/Admin@ru.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/ru.com/users/Admin@ru.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/ru.com/users/Admin@ru.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/ru.com/users/Admin@ru.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
     # - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - certification

