# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.certification-network.com:
    container_name: orderer.certification-network.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # TLS settings - Set to false for simplicity in this example. In production, TLS should be enabled.
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/certification-network.com/orderers/orderer.certification-network.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/certification-network.com/orderers/orderer.certification-network.com/tls/:/var/hyperledger/orderer/tls
      - orderer.certification-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.iit.certification-network.com:
    container_name: peer0.iit.certification-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.iit.certification-network.com
      - CORE_PEER_ADDRESS=peer0.iit.certification-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.iit.certification-network.com:7052 # Port changed to avoid conflicts
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 # Port changed to avoid conflicts
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.iit.certification-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.iit.certification-network.com:7051
      - CORE_PEER_LOCALMSPID=iitMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls:/etc/hyperledger/fabric/tls
      - peer0.iit.certification-network.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.iit.certification-network.com:
    container_name: peer1.iit.certification-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.iit.certification-network.com
      - CORE_PEER_ADDRESS=peer1.iit.certification-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.iit.certification-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.iit.certification-network.com:7051
      - CORE_PEER_LOCALMSPID=iitMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/iit.certification-network.com/peers/peer1.iit.certification-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/iit.certification-network.com/peers/peer1.iit.certification-network.com/tls:/etc/hyperledger/fabric/tls
      - peer1.iit.certification-network.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.mhrd.certification-network.com:
    container_name: peer0.mhrd.certification-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mhrd.certification-network.com
      - CORE_PEER_ADDRESS=peer0.mhrd.certification-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mhrd.certification-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.mhrd.certification-network.com:10051
      - CORE_PEER_LOCALMSPID=mhrdMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/mhrd.certification-network.com/peers/peer0.mhrd.certification-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/mhrd.certification-network.com/peers/peer0.mhrd.certification-network.com/tls:/etc/hyperledger/fabric/tls
      - peer0.mhrd.certification-network.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.mhrd.certification-network.com:
    container_name: peer1.mhrd.certification-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mhrd.certification-network.com
      - CORE_PEER_ADDRESS=peer1.mhrd.certification-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mhrd.certification-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mhrd.certification-network.com:9051
      - CORE_PEER_LOCALMSPID=mhrdMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/mhrd.certification-network.com/peers/peer1.mhrd.certification-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/mhrd.certification-network.com/peers/peer1.mhrd.certification-network.com/tls:/etc/hyperledger/fabric/tls
      - peer1.mhrd.certification-network.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.upgrad.certification-network.com:
    container_name: peer0.upgrad.certification-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.upgrad.certification-network.com
      - CORE_PEER_ADDRESS=peer0.upgrad.certification-network.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.upgrad.certification-network.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.upgrad.certification-network.com:12051
      - CORE_PEER_LOCALMSPID=upgradMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/upgrad.certification-network.com/peers/peer0.upgrad.certification-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/upgrad.certification-network.com/peers/peer0.upgrad.certification-network.com/tls:/etc/hyperledger/fabric/tls
      - peer0.upgrad.certification-network.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.upgrad.certification-network.com:
    container_name: peer1.upgrad.certification-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.upgrad.certification-network.com
      - CORE_PEER_ADDRESS=peer1.upgrad.certification-network.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.upgrad.certification-network.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.upgrad.certification-network.com:11051
      - CORE_PEER_LOCALMSPID=upgradMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/upgrad.certification-network.com/peers/peer1.upgrad.certification-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/upgrad.certification-network.com/peers/peer1.upgrad.certification-network.com/tls:/etc/hyperledger/fabric/tls
      - peer1.upgrad.certification-network.com:/var/hyperledger/production
    ports:
      - 12051:12051
