# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.com:
    container_name: orderer.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # TLS settings - Set to false for simplicity in this example. In production, TLS should be enabled.
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/com/orderers/orderer.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/com/orderers/orderer.com/tls/:/var/hyperledger/orderer/tls
      - orderer.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.ru.com:
    container_name: peer0.ru.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ru.com
      - CORE_PEER_ADDRESS=peer0.ru.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ru.com:7052 # Port changed to avoid conflicts
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 # Port changed to avoid conflicts
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ru.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ru.com:7051
      - CORE_PEER_LOCALMSPID=ruMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/ru.com/peers/peer0.ru.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/ru.com/peers/peer0.ru.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ru.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.ru.com:
    container_name: peer1.ru.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ru.com
      - CORE_PEER_ADDRESS=peer1.ru.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ru.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ru.com:7051
      - CORE_PEER_LOCALMSPID=ruMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/ru.com/peers/peer1.ru.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/ru.com/peers/peer1.ru.com/tls:/etc/hyperledger/fabric/tls
      - peer1.ru.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.me.com:
    container_name: peer0.me.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.me.com
      - CORE_PEER_ADDRESS=peer0.me.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.me.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.me.com:10051
      - CORE_PEER_LOCALMSPID=meMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/me.com/peers/peer0.me.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/me.com/peers/peer0.me.com/tls:/etc/hyperledger/fabric/tls
      - peer0.me.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.me.com:
    container_name: peer1.me.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.me.com
      - CORE_PEER_ADDRESS=peer1.me.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.me.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.me.com:9051
      - CORE_PEER_LOCALMSPID=meMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/me.com/peers/peer1.me.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/me.com/peers/peer1.me.com/tls:/etc/hyperledger/fabric/tls
      - peer1.me.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.authenticator.com:
    container_name: peer0.authenticator.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.authenticator.com
      - CORE_PEER_ADDRESS=peer0.authenticator.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.authenticator.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.authenticator.com:12051
      - CORE_PEER_LOCALMSPID=authenticatorMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/authenticator.com/peers/peer0.authenticator.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/authenticator.com/peers/peer0.authenticator.com/tls:/etc/hyperledger/fabric/tls
      - peer0.authenticator.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.authenticator.com:
    container_name: peer1.authenticator.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.authenticator.com
      - CORE_PEER_ADDRESS=peer1.authenticator.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.authenticator.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.authenticator.com:11051
      - CORE_PEER_LOCALMSPID=authenticatorMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/authenticator.com/peers/peer1.authenticator.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/authenticator.com/peers/peer1.authenticator.com/tls:/etc/hyperledger/fabric/tls
      - peer1.authenticator.com:/var/hyperledger/production
    ports:
      - 12051:12051
